# Hyprland appearance configuration by BigBenKoala

# Source color variables
source = ~/.config/hypr/colors.conf

# General window settings
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = $color2
    col.inactive_border = $color1
    layout = dwindle
    resize_on_border = true
}

# Decorations
decoration {
    rounding = 20
    inactive_opacity = 0.9
    active_opacity = 1.0
    blur {
        enabled = true
        size = 4
        passes = 2
        new_optimizations = true
        ignore_opacity = false
    }
}

# Animations
animations {
    enabled = true
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 5, myBezier
    animation = windowsOut, 1, 5, default, popin 80%
    animation = border, 1, 8, default
    animation = fade, 1, 5, default
    animation = workspaces, 1, 4, default
}

# Keep applications fully opaque.
windowrule = no_blur on, opacity 1.0 override,  match:class zen
