wallpaper {
    monitor = DP-3
    path = ~/Pictures/Wallpaper/peugeot.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = ~/Pictures/Wallpaper/peugeot.png
    fit_mode = cover
}

splash = false
