# Hyprland configuation by BigBenKoala.
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = HYPRCURSOR_SIZE,24
env = XCURSOR_SIZE,24

# Programms to execute
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = snappy-switcher --daemon
exec-once = hyprpaper
exec-once = hyprpm reload

# Configuration files
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/appearance.conf

input {
    accel_profile = flat
    sensitivity = 0
}

device {
    name = logitech-pro-x-1
    accel_profile = flat
    sensitivity = 0
}
