# Hyprland configuation by BigBenKoala.

# Configuration files
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/appearance.conf
source = ~/.config/hypr/environment.conf


# Programms to execute
exec-once = hyprpaper

# Disable pointer acceleration globally
input:force_no_accel = 1
input:accel_profile = flat

env = HYPRCURSOR_SIZE,24
