# Hyprland keybinds configuation by BigBenKoala.

$terminal = ghostty
$browser = zen-browser
$explorer = nautilus
$chat = discord
$lock = hyprlock

# Bind to exit hyprland.
bind = SUPER, Escape, exit,

# Bind to reaload hyprland.
bind = SUPER SHIFT, R, exec, hyprctl reload

# Bind to exit or force exit application.
bind = SUPER, Q, killactive,
bind = SUPER SHIFT, Q, exec, hyprctl kill

# Bind to fullscreen or maximize application.
bind = SUPER, F, fullscreen, 1
bind = SUPER SHIFT, F, fullscreen, 0

# Bind to toggle floating and interact with floating applications.
bind = SUPER, V, togglefloating,
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

# Bind to resize an application.
bind = SUPER SHIFT, left, resizeactive, -20 0
bind = SUPER SHIFT, right, resizeactive, 20 0
bind = SUPER SHIFT, up, resizeactive, 0 -20
bind = SUPER SHIFT, down, resizeactive, 0 20

# Bind to move applications positions.
bind = SUPER ALT, left, movewindow, l
bind = SUPER ALT, right, movewindow, r
bind = SUPER ALT, up, movewindow, u
bind = SUPER ALT, down, movewindow, d

# Bind to swap an application position with another application.
bind = SUPER CTRL, left, swapwindow, l
bind = SUPER CTRL, right, swapwindow, r
bind = SUPER CTRL, up, swapwindow, u
bind = SUPER CTRL, down, swapwindow, d

# Bind to move focus between applications.
bind = SUPER, left, movefocus, l
bind = SUPER, right, movefocus, r
bind = SUPER, up, movefocus, u
bind = SUPER, down, movefocus, d

# Bind to switch workspace.
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, mouse_down, workspace, e+1
bind = SUPER, mouse_up, workspace, e-1

# Bind to move an application to a workspace.
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2

# Bind to open applications.
bind = SUPER, return, exec, $terminal
bind = SUPER, B, exec, $browser
bind = SUPER, E, exec, $explorer
bind = SUPER, D, exec, $chat
bind = SUPER, L, exec, $lock

# Toggle show/hide all windows on the current workspace (calls helper script)
bind = SUPER, H, exec, ~/.config/hypr/toggle_show_desktop.sh

# Take a region screenshot and saves it to pictures
bind = SUPER SHIFT, S, exec, grim -g "$(slurp)" ~/Pictures/$(date +%Y-%m-%d_%H-%M-%S).png
